kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: brokero-brokero-ss-0
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    ActiveMQArtemis: brokero
    application: brokero-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-70dbe894-c490-42e5-a02b-7ceb28901e79